language: scala
scala:
  - 2.10.5
jdk:
  - openjdk7
sudo: false
before_install:
  - pip install --user codecov
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt -jvm-opts travis/jvmopts.test test
after_success:
  - codecov
